name: HWKMDElectronCI

on: 
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - dev
jobs:
  job-macos-build:
    name: Build (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Build GUI
      env:
        CI: ""
      run: |
        cd electron/ui
        npm install
        npm run build-electron

    - name: Build Electron App
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        cd electron
        npm install
        npm run dist
        tar -czvf hw-kmd-rewards-claim-desktop-osx-${{ env.BASE_BRANCH }}.tar.gz dist

    - name: Upload hw-kmd-rewards-claim-desktop-osx-${{ env.BASE_BRANCH }}.tar.gz as artifact
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-osx-${{ env.BASE_BRANCH }}
        path: ./electron/hw-kmd-rewards-claim-desktop-osx-${{ env.BASE_BRANCH }}.tar.gz

  job-linux-build:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Build GUI
      env:
        CI: ""
      run: |
        cd electron/ui
        npm install
        npm run build-electron

    - name: Build Electron App
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        cd electron
        npm install
        npm run dist
        tar -czvf hw-kmd-rewards-claim-desktop-linux-${{ env.BASE_BRANCH  }}.tar.gz dist

    - name: Upload hw-kmd-rewards-claim-desktop-linux-${{ env.BASE_BRANCH  }}.tar.gz as artifact
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-linux-${{ env.BASE_BRANCH  }}
        path: ./electron/hw-kmd-rewards-claim-desktop-linux-${{ env.BASE_BRANCH  }}.tar.gz

  job-win-build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true

    - name: Build GUI
      env:
        CI: ""
      run: |
        cd electron/ui
        npm install
        npm run build-electron

    - name: Build Electron App
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        cd electron
        npm install
        npm run dist
        tar -czvf hw-kmd-rewards-claim-desktop-win-${{ env.BASE_BRANCH }}.tar.gz dist

    - name: Upload hw-kmd-rewards-claim-desktop-win-${{ env.BASE_BRANCH }}.tar.gz as artifact
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      uses: actions/upload-artifact@v1
      with:
        name: hw-kmd-rewards-claim-desktop-win-${{ env.BASE_BRANCH }}
        path: ./electron/hw-kmd-rewards-claim-desktop-win-${{ env.BASE_BRANCH }}.tar.gz